// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_vkrMYfrf4yH3uKIJ-OtnWn9MilW8Xg',
    appId: '1:919542236331:web:0493b9f60b262e6c5263ee',
    messagingSenderId: '919542236331',
    projectId: 'todoapp-63d1b',
    authDomain: 'todoapp-63d1b.firebaseapp.com',
    storageBucket: 'todoapp-63d1b.firebasestorage.app',
    measurementId: 'G-H0XBC5SV3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2D87_8AeW99SYdOpZWH70SgBS_Rj8St8',
    appId: '1:919542236331:android:8bcea9e7e7e3c97e5263ee',
    messagingSenderId: '919542236331',
    projectId: 'todoapp-63d1b',
    storageBucket: 'todoapp-63d1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk8zuV3L8EWTiS57z1E3F52cKO5uBEHv8',
    appId: '1:919542236331:ios:4ef034d1b8c80c2f5263ee',
    messagingSenderId: '919542236331',
    projectId: 'todoapp-63d1b',
    storageBucket: 'todoapp-63d1b.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk8zuV3L8EWTiS57z1E3F52cKO5uBEHv8',
    appId: '1:919542236331:ios:4ef034d1b8c80c2f5263ee',
    messagingSenderId: '919542236331',
    projectId: 'todoapp-63d1b',
    storageBucket: 'todoapp-63d1b.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB_vkrMYfrf4yH3uKIJ-OtnWn9MilW8Xg',
    appId: '1:919542236331:web:281b6bf50792a9d75263ee',
    messagingSenderId: '919542236331',
    projectId: 'todoapp-63d1b',
    authDomain: 'todoapp-63d1b.firebaseapp.com',
    storageBucket: 'todoapp-63d1b.firebasestorage.app',
    measurementId: 'G-G43FZ3VEHJ',
  );
}
